/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * MS Access Learning Tool API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateDatabaseRequest,
  CreateEmbedRequest,
  CreateRecordRequest,
  CreateTableRequest,
  Database,
  EmbedDatabaseSnapshot,
  EmbedToken,
  ErrorResponse,
  HealthStatus,
  ListDatabasesParams,
  ListRecordsParams,
  Record,
  Table,
  TableWithFields,
  UpdateDatabaseRequest,
  UpdateRecordRequest,
  UpdateTableRequest,
} from "./api.schemas";

import { customFetch } from "./custom-fetch";
import type { ErrorType, BodyType } from "./custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/ds/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/ds/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List all databases for a user
 */
export const getListDatabasesUrl = (params: ListDatabasesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/ds/databases?${stringifiedParams}`
    : `/api/ds/databases`;
};

export const listDatabases = async (
  params: ListDatabasesParams,
  options?: RequestInit,
): Promise<Database[]> => {
  return customFetch<Database[]>(getListDatabasesUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListDatabasesQueryKey = (params?: ListDatabasesParams) => {
  return [`/api/ds/databases`, ...(params ? [params] : [])] as const;
};

export const getListDatabasesQueryOptions = <
  TData = Awaited<ReturnType<typeof listDatabases>>,
  TError = ErrorType<unknown>,
>(
  params: ListDatabasesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listDatabases>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListDatabasesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listDatabases>>> = ({
    signal,
  }) => listDatabases(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listDatabases>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListDatabasesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listDatabases>>
>;
export type ListDatabasesQueryError = ErrorType<unknown>;

/**
 * @summary List all databases for a user
 */

export function useListDatabases<
  TData = Awaited<ReturnType<typeof listDatabases>>,
  TError = ErrorType<unknown>,
>(
  params: ListDatabasesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listDatabases>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListDatabasesQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a new database
 */
export const getCreateDatabaseUrl = () => {
  return `/api/ds/databases`;
};

export const createDatabase = async (
  createDatabaseRequest: CreateDatabaseRequest,
  options?: RequestInit,
): Promise<Database> => {
  return customFetch<Database>(getCreateDatabaseUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createDatabaseRequest),
  });
};

export const getCreateDatabaseMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createDatabase>>,
    TError,
    { data: BodyType<CreateDatabaseRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createDatabase>>,
  TError,
  { data: BodyType<CreateDatabaseRequest> },
  TContext
> => {
  const mutationKey = ["createDatabase"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createDatabase>>,
    { data: BodyType<CreateDatabaseRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createDatabase(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateDatabaseMutationResult = NonNullable<
  Awaited<ReturnType<typeof createDatabase>>
>;
export type CreateDatabaseMutationBody = BodyType<CreateDatabaseRequest>;
export type CreateDatabaseMutationError = ErrorType<unknown>;

/**
 * @summary Create a new database
 */
export const useCreateDatabase = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createDatabase>>,
    TError,
    { data: BodyType<CreateDatabaseRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createDatabase>>,
  TError,
  { data: BodyType<CreateDatabaseRequest> },
  TContext
> => {
  return useMutation(getCreateDatabaseMutationOptions(options));
};

/**
 * @summary Get a database by ID
 */
export const getGetDatabaseUrl = (databaseId: number) => {
  return `/api/ds/databases/${databaseId}`;
};

export const getDatabase = async (
  databaseId: number,
  options?: RequestInit,
): Promise<Database> => {
  return customFetch<Database>(getGetDatabaseUrl(databaseId), {
    ...options,
    method: "GET",
  });
};

export const getGetDatabaseQueryKey = (databaseId: number) => {
  return [`/api/ds/databases/${databaseId}`] as const;
};

export const getGetDatabaseQueryOptions = <
  TData = Awaited<ReturnType<typeof getDatabase>>,
  TError = ErrorType<ErrorResponse>,
>(
  databaseId: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getDatabase>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDatabaseQueryKey(databaseId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDatabase>>> = ({
    signal,
  }) => getDatabase(databaseId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!databaseId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getDatabase>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetDatabaseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDatabase>>
>;
export type GetDatabaseQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get a database by ID
 */

export function useGetDatabase<
  TData = Awaited<ReturnType<typeof getDatabase>>,
  TError = ErrorType<ErrorResponse>,
>(
  databaseId: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getDatabase>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetDatabaseQueryOptions(databaseId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update a database
 */
export const getUpdateDatabaseUrl = (databaseId: number) => {
  return `/api/ds/databases/${databaseId}`;
};

export const updateDatabase = async (
  databaseId: number,
  updateDatabaseRequest: UpdateDatabaseRequest,
  options?: RequestInit,
): Promise<Database> => {
  return customFetch<Database>(getUpdateDatabaseUrl(databaseId), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateDatabaseRequest),
  });
};

export const getUpdateDatabaseMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateDatabase>>,
    TError,
    { databaseId: number; data: BodyType<UpdateDatabaseRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateDatabase>>,
  TError,
  { databaseId: number; data: BodyType<UpdateDatabaseRequest> },
  TContext
> => {
  const mutationKey = ["updateDatabase"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateDatabase>>,
    { databaseId: number; data: BodyType<UpdateDatabaseRequest> }
  > = (props) => {
    const { databaseId, data } = props ?? {};

    return updateDatabase(databaseId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateDatabaseMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateDatabase>>
>;
export type UpdateDatabaseMutationBody = BodyType<UpdateDatabaseRequest>;
export type UpdateDatabaseMutationError = ErrorType<unknown>;

/**
 * @summary Update a database
 */
export const useUpdateDatabase = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateDatabase>>,
    TError,
    { databaseId: number; data: BodyType<UpdateDatabaseRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateDatabase>>,
  TError,
  { databaseId: number; data: BodyType<UpdateDatabaseRequest> },
  TContext
> => {
  return useMutation(getUpdateDatabaseMutationOptions(options));
};

/**
 * @summary Delete a database
 */
export const getDeleteDatabaseUrl = (databaseId: number) => {
  return `/api/ds/databases/${databaseId}`;
};

export const deleteDatabase = async (
  databaseId: number,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getDeleteDatabaseUrl(databaseId), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteDatabaseMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteDatabase>>,
    TError,
    { databaseId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteDatabase>>,
  TError,
  { databaseId: number },
  TContext
> => {
  const mutationKey = ["deleteDatabase"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteDatabase>>,
    { databaseId: number }
  > = (props) => {
    const { databaseId } = props ?? {};

    return deleteDatabase(databaseId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteDatabaseMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteDatabase>>
>;

export type DeleteDatabaseMutationError = ErrorType<unknown>;

/**
 * @summary Delete a database
 */
export const useDeleteDatabase = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteDatabase>>,
    TError,
    { databaseId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteDatabase>>,
  TError,
  { databaseId: number },
  TContext
> => {
  return useMutation(getDeleteDatabaseMutationOptions(options));
};

/**
 * @summary List all tables in a database
 */
export const getListTablesUrl = (databaseId: number) => {
  return `/api/ds/databases/${databaseId}/tables`;
};

export const listTables = async (
  databaseId: number,
  options?: RequestInit,
): Promise<Table[]> => {
  return customFetch<Table[]>(getListTablesUrl(databaseId), {
    ...options,
    method: "GET",
  });
};

export const getListTablesQueryKey = (databaseId: number) => {
  return [`/api/ds/databases/${databaseId}/tables`] as const;
};

export const getListTablesQueryOptions = <
  TData = Awaited<ReturnType<typeof listTables>>,
  TError = ErrorType<unknown>,
>(
  databaseId: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listTables>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListTablesQueryKey(databaseId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listTables>>> = ({
    signal,
  }) => listTables(databaseId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!databaseId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listTables>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListTablesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listTables>>
>;
export type ListTablesQueryError = ErrorType<unknown>;

/**
 * @summary List all tables in a database
 */

export function useListTables<
  TData = Awaited<ReturnType<typeof listTables>>,
  TError = ErrorType<unknown>,
>(
  databaseId: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listTables>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListTablesQueryOptions(databaseId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a new table
 */
export const getCreateTableUrl = (databaseId: number) => {
  return `/api/ds/databases/${databaseId}/tables`;
};

export const createTable = async (
  databaseId: number,
  createTableRequest: CreateTableRequest,
  options?: RequestInit,
): Promise<Table> => {
  return customFetch<Table>(getCreateTableUrl(databaseId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createTableRequest),
  });
};

export const getCreateTableMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createTable>>,
    TError,
    { databaseId: number; data: BodyType<CreateTableRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createTable>>,
  TError,
  { databaseId: number; data: BodyType<CreateTableRequest> },
  TContext
> => {
  const mutationKey = ["createTable"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createTable>>,
    { databaseId: number; data: BodyType<CreateTableRequest> }
  > = (props) => {
    const { databaseId, data } = props ?? {};

    return createTable(databaseId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateTableMutationResult = NonNullable<
  Awaited<ReturnType<typeof createTable>>
>;
export type CreateTableMutationBody = BodyType<CreateTableRequest>;
export type CreateTableMutationError = ErrorType<unknown>;

/**
 * @summary Create a new table
 */
export const useCreateTable = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createTable>>,
    TError,
    { databaseId: number; data: BodyType<CreateTableRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createTable>>,
  TError,
  { databaseId: number; data: BodyType<CreateTableRequest> },
  TContext
> => {
  return useMutation(getCreateTableMutationOptions(options));
};

/**
 * @summary Get a table with its fields
 */
export const getGetTableUrl = (databaseId: number, tableId: number) => {
  return `/api/ds/databases/${databaseId}/tables/${tableId}`;
};

export const getTable = async (
  databaseId: number,
  tableId: number,
  options?: RequestInit,
): Promise<TableWithFields> => {
  return customFetch<TableWithFields>(getGetTableUrl(databaseId, tableId), {
    ...options,
    method: "GET",
  });
};

export const getGetTableQueryKey = (databaseId: number, tableId: number) => {
  return [`/api/ds/databases/${databaseId}/tables/${tableId}`] as const;
};

export const getGetTableQueryOptions = <
  TData = Awaited<ReturnType<typeof getTable>>,
  TError = ErrorType<unknown>,
>(
  databaseId: number,
  tableId: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getTable>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetTableQueryKey(databaseId, tableId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTable>>> = ({
    signal,
  }) => getTable(databaseId, tableId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!(databaseId && tableId),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getTable>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type GetTableQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTable>>
>;
export type GetTableQueryError = ErrorType<unknown>;

/**
 * @summary Get a table with its fields
 */

export function useGetTable<
  TData = Awaited<ReturnType<typeof getTable>>,
  TError = ErrorType<unknown>,
>(
  databaseId: number,
  tableId: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getTable>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetTableQueryOptions(databaseId, tableId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update a table (name and fields)
 */
export const getUpdateTableUrl = (databaseId: number, tableId: number) => {
  return `/api/ds/databases/${databaseId}/tables/${tableId}`;
};

export const updateTable = async (
  databaseId: number,
  tableId: number,
  updateTableRequest: UpdateTableRequest,
  options?: RequestInit,
): Promise<TableWithFields> => {
  return customFetch<TableWithFields>(getUpdateTableUrl(databaseId, tableId), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateTableRequest),
  });
};

export const getUpdateTableMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateTable>>,
    TError,
    { databaseId: number; tableId: number; data: BodyType<UpdateTableRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateTable>>,
  TError,
  { databaseId: number; tableId: number; data: BodyType<UpdateTableRequest> },
  TContext
> => {
  const mutationKey = ["updateTable"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateTable>>,
    { databaseId: number; tableId: number; data: BodyType<UpdateTableRequest> }
  > = (props) => {
    const { databaseId, tableId, data } = props ?? {};

    return updateTable(databaseId, tableId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateTableMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateTable>>
>;
export type UpdateTableMutationBody = BodyType<UpdateTableRequest>;
export type UpdateTableMutationError = ErrorType<unknown>;

/**
 * @summary Update a table (name and fields)
 */
export const useUpdateTable = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateTable>>,
    TError,
    { databaseId: number; tableId: number; data: BodyType<UpdateTableRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateTable>>,
  TError,
  { databaseId: number; tableId: number; data: BodyType<UpdateTableRequest> },
  TContext
> => {
  return useMutation(getUpdateTableMutationOptions(options));
};

/**
 * @summary Delete a table
 */
export const getDeleteTableUrl = (databaseId: number, tableId: number) => {
  return `/api/ds/databases/${databaseId}/tables/${tableId}`;
};

export const deleteTable = async (
  databaseId: number,
  tableId: number,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getDeleteTableUrl(databaseId, tableId), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteTableMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteTable>>,
    TError,
    { databaseId: number; tableId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteTable>>,
  TError,
  { databaseId: number; tableId: number },
  TContext
> => {
  const mutationKey = ["deleteTable"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteTable>>,
    { databaseId: number; tableId: number }
  > = (props) => {
    const { databaseId, tableId } = props ?? {};

    return deleteTable(databaseId, tableId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteTableMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteTable>>
>;

export type DeleteTableMutationError = ErrorType<unknown>;

/**
 * @summary Delete a table
 */
export const useDeleteTable = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteTable>>,
    TError,
    { databaseId: number; tableId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteTable>>,
  TError,
  { databaseId: number; tableId: number },
  TContext
> => {
  return useMutation(getDeleteTableMutationOptions(options));
};

/**
 * @summary List records in a table with optional sorting/filtering
 */
export const getListRecordsUrl = (
  databaseId: number,
  tableId: number,
  params?: ListRecordsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/ds/databases/${databaseId}/tables/${tableId}/records?${stringifiedParams}`
    : `/api/ds/databases/${databaseId}/tables/${tableId}/records`;
};

export const listRecords = async (
  databaseId: number,
  tableId: number,
  params?: ListRecordsParams,
  options?: RequestInit,
): Promise<Record[]> => {
  return customFetch<Record[]>(getListRecordsUrl(databaseId, tableId, params), {
    ...options,
    method: "GET",
  });
};

export const getListRecordsQueryKey = (
  databaseId: number,
  tableId: number,
  params?: ListRecordsParams,
) => {
  return [
    `/api/ds/databases/${databaseId}/tables/${tableId}/records`,
    ...(params ? [params] : []),
  ] as const;
};

export const getListRecordsQueryOptions = <
  TData = Awaited<ReturnType<typeof listRecords>>,
  TError = ErrorType<unknown>,
>(
  databaseId: number,
  tableId: number,
  params?: ListRecordsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listRecords>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getListRecordsQueryKey(databaseId, tableId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listRecords>>> = ({
    signal,
  }) => listRecords(databaseId, tableId, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!(databaseId && tableId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listRecords>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListRecordsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listRecords>>
>;
export type ListRecordsQueryError = ErrorType<unknown>;

/**
 * @summary List records in a table with optional sorting/filtering
 */

export function useListRecords<
  TData = Awaited<ReturnType<typeof listRecords>>,
  TError = ErrorType<unknown>,
>(
  databaseId: number,
  tableId: number,
  params?: ListRecordsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listRecords>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListRecordsQueryOptions(
    databaseId,
    tableId,
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a new record
 */
export const getCreateRecordUrl = (databaseId: number, tableId: number) => {
  return `/api/ds/databases/${databaseId}/tables/${tableId}/records`;
};

export const createRecord = async (
  databaseId: number,
  tableId: number,
  createRecordRequest: CreateRecordRequest,
  options?: RequestInit,
): Promise<Record> => {
  return customFetch<Record>(getCreateRecordUrl(databaseId, tableId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createRecordRequest),
  });
};

export const getCreateRecordMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createRecord>>,
    TError,
    {
      databaseId: number;
      tableId: number;
      data: BodyType<CreateRecordRequest>;
    },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createRecord>>,
  TError,
  { databaseId: number; tableId: number; data: BodyType<CreateRecordRequest> },
  TContext
> => {
  const mutationKey = ["createRecord"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createRecord>>,
    { databaseId: number; tableId: number; data: BodyType<CreateRecordRequest> }
  > = (props) => {
    const { databaseId, tableId, data } = props ?? {};

    return createRecord(databaseId, tableId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateRecordMutationResult = NonNullable<
  Awaited<ReturnType<typeof createRecord>>
>;
export type CreateRecordMutationBody = BodyType<CreateRecordRequest>;
export type CreateRecordMutationError = ErrorType<unknown>;

/**
 * @summary Create a new record
 */
export const useCreateRecord = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createRecord>>,
    TError,
    {
      databaseId: number;
      tableId: number;
      data: BodyType<CreateRecordRequest>;
    },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createRecord>>,
  TError,
  { databaseId: number; tableId: number; data: BodyType<CreateRecordRequest> },
  TContext
> => {
  return useMutation(getCreateRecordMutationOptions(options));
};

/**
 * @summary Update a record
 */
export const getUpdateRecordUrl = (
  databaseId: number,
  tableId: number,
  recordId: number,
) => {
  return `/api/ds/databases/${databaseId}/tables/${tableId}/records/${recordId}`;
};

export const updateRecord = async (
  databaseId: number,
  tableId: number,
  recordId: number,
  updateRecordRequest: UpdateRecordRequest,
  options?: RequestInit,
): Promise<Record> => {
  return customFetch<Record>(
    getUpdateRecordUrl(databaseId, tableId, recordId),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateRecordRequest),
    },
  );
};

export const getUpdateRecordMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateRecord>>,
    TError,
    {
      databaseId: number;
      tableId: number;
      recordId: number;
      data: BodyType<UpdateRecordRequest>;
    },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateRecord>>,
  TError,
  {
    databaseId: number;
    tableId: number;
    recordId: number;
    data: BodyType<UpdateRecordRequest>;
  },
  TContext
> => {
  const mutationKey = ["updateRecord"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateRecord>>,
    {
      databaseId: number;
      tableId: number;
      recordId: number;
      data: BodyType<UpdateRecordRequest>;
    }
  > = (props) => {
    const { databaseId, tableId, recordId, data } = props ?? {};

    return updateRecord(databaseId, tableId, recordId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateRecordMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateRecord>>
>;
export type UpdateRecordMutationBody = BodyType<UpdateRecordRequest>;
export type UpdateRecordMutationError = ErrorType<unknown>;

/**
 * @summary Update a record
 */
export const useUpdateRecord = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateRecord>>,
    TError,
    {
      databaseId: number;
      tableId: number;
      recordId: number;
      data: BodyType<UpdateRecordRequest>;
    },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateRecord>>,
  TError,
  {
    databaseId: number;
    tableId: number;
    recordId: number;
    data: BodyType<UpdateRecordRequest>;
  },
  TContext
> => {
  return useMutation(getUpdateRecordMutationOptions(options));
};

/**
 * @summary Delete a record
 */
export const getDeleteRecordUrl = (
  databaseId: number,
  tableId: number,
  recordId: number,
) => {
  return `/api/ds/databases/${databaseId}/tables/${tableId}/records/${recordId}`;
};

export const deleteRecord = async (
  databaseId: number,
  tableId: number,
  recordId: number,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getDeleteRecordUrl(databaseId, tableId, recordId), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteRecordMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteRecord>>,
    TError,
    { databaseId: number; tableId: number; recordId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteRecord>>,
  TError,
  { databaseId: number; tableId: number; recordId: number },
  TContext
> => {
  const mutationKey = ["deleteRecord"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteRecord>>,
    { databaseId: number; tableId: number; recordId: number }
  > = (props) => {
    const { databaseId, tableId, recordId } = props ?? {};

    return deleteRecord(databaseId, tableId, recordId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteRecordMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteRecord>>
>;

export type DeleteRecordMutationError = ErrorType<unknown>;

/**
 * @summary Delete a record
 */
export const useDeleteRecord = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteRecord>>,
    TError,
    { databaseId: number; tableId: number; recordId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteRecord>>,
  TError,
  { databaseId: number; tableId: number; recordId: number },
  TContext
> => {
  return useMutation(getDeleteRecordMutationOptions(options));
};

/**
 * @summary Create an embed token for a database
 */
export const getCreateEmbedUrl = () => {
  return `/api/ds/embeds`;
};

export const createEmbed = async (
  createEmbedRequest: CreateEmbedRequest,
  options?: RequestInit,
): Promise<EmbedToken> => {
  return customFetch<EmbedToken>(getCreateEmbedUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createEmbedRequest),
  });
};

export const getCreateEmbedMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createEmbed>>,
    TError,
    { data: BodyType<CreateEmbedRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createEmbed>>,
  TError,
  { data: BodyType<CreateEmbedRequest> },
  TContext
> => {
  const mutationKey = ["createEmbed"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createEmbed>>,
    { data: BodyType<CreateEmbedRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createEmbed(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateEmbedMutationResult = NonNullable<
  Awaited<ReturnType<typeof createEmbed>>
>;
export type CreateEmbedMutationBody = BodyType<CreateEmbedRequest>;
export type CreateEmbedMutationError = ErrorType<unknown>;

/**
 * @summary Create an embed token for a database
 */
export const useCreateEmbed = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createEmbed>>,
    TError,
    { data: BodyType<CreateEmbedRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createEmbed>>,
  TError,
  { data: BodyType<CreateEmbedRequest> },
  TContext
> => {
  return useMutation(getCreateEmbedMutationOptions(options));
};

/**
 * @summary Get a database snapshot by embed token
 */
export const getGetEmbedDatabaseUrl = (token: string) => {
  return `/api/ds/embeds/${token}`;
};

export const getEmbedDatabase = async (
  token: string,
  options?: RequestInit,
): Promise<EmbedDatabaseSnapshot> => {
  return customFetch<EmbedDatabaseSnapshot>(getGetEmbedDatabaseUrl(token), {
    ...options,
    method: "GET",
  });
};

export const getGetEmbedDatabaseQueryKey = (token: string) => {
  return [`/api/ds/embeds/${token}`] as const;
};

export const getGetEmbedDatabaseQueryOptions = <
  TData = Awaited<ReturnType<typeof getEmbedDatabase>>,
  TError = ErrorType<ErrorResponse>,
>(
  token: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getEmbedDatabase>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetEmbedDatabaseQueryKey(token);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getEmbedDatabase>>
  > = ({ signal }) => getEmbedDatabase(token, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!token,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getEmbedDatabase>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetEmbedDatabaseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getEmbedDatabase>>
>;
export type GetEmbedDatabaseQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get a database snapshot by embed token
 */

export function useGetEmbedDatabase<
  TData = Awaited<ReturnType<typeof getEmbedDatabase>>,
  TError = ErrorType<ErrorResponse>,
>(
  token: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getEmbedDatabase>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetEmbedDatabaseQueryOptions(token, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
