/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * MS Access Learning Tool API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
}

export interface Database {
  id: number;
  name: string;
  userId: string;
  taskDescription?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface CreateDatabaseRequest {
  name: string;
  userId: string;
}

export interface UpdateDatabaseRequest {
  name: string;
  taskDescription?: string | null;
}

export type FieldDefinitionFieldType =
  (typeof FieldDefinitionFieldType)[keyof typeof FieldDefinitionFieldType];

export const FieldDefinitionFieldType = {
  text: "text",
  number: "number",
  date: "date",
  boolean: "boolean",
  autonumber: "autonumber",
} as const;

export interface FieldDefinition {
  id: number;
  name: string;
  fieldType: FieldDefinitionFieldType;
  isRequired: boolean;
  isPrimaryKey: boolean;
  sortOrder: number;
  caption?: string | null;
  defaultValue?: string | null;
  fieldSize?: number | null;
  description?: string | null;
}

export interface Table {
  id: number;
  name: string;
  databaseId: number;
  createdAt: string;
  updatedAt: string;
}

export interface TableWithFields {
  id: number;
  name: string;
  databaseId: number;
  fields: FieldDefinition[];
  createdAt: string;
  updatedAt: string;
}

export type CreateFieldRequestFieldType =
  (typeof CreateFieldRequestFieldType)[keyof typeof CreateFieldRequestFieldType];

export const CreateFieldRequestFieldType = {
  text: "text",
  number: "number",
  date: "date",
  boolean: "boolean",
  autonumber: "autonumber",
} as const;

export interface CreateFieldRequest {
  name: string;
  fieldType: CreateFieldRequestFieldType;
  isRequired: boolean;
  isPrimaryKey: boolean;
  sortOrder: number;
}

export interface CreateTableRequest {
  name: string;
  fields: CreateFieldRequest[];
}

export type UpdateFieldRequestFieldType =
  (typeof UpdateFieldRequestFieldType)[keyof typeof UpdateFieldRequestFieldType];

export const UpdateFieldRequestFieldType = {
  text: "text",
  number: "number",
  date: "date",
  boolean: "boolean",
  autonumber: "autonumber",
} as const;

export interface UpdateFieldRequest {
  id?: number;
  name: string;
  fieldType: UpdateFieldRequestFieldType;
  isRequired: boolean;
  isPrimaryKey: boolean;
  sortOrder: number;
  caption?: string | null;
  defaultValue?: string | null;
  fieldSize?: number | null;
  description?: string | null;
}

export interface UpdateTableRequest {
  name: string;
  fields: UpdateFieldRequest[];
}

export type RecordData = { [key: string]: unknown };

export interface Record {
  id: number;
  tableId: number;
  data: RecordData;
  createdAt: string;
  updatedAt: string;
}

export type CreateRecordRequestData = { [key: string]: unknown };

export interface CreateRecordRequest {
  data: CreateRecordRequestData;
}

export type UpdateRecordRequestData = { [key: string]: unknown };

export interface UpdateRecordRequest {
  data: UpdateRecordRequestData;
}

export interface CreateEmbedRequest {
  databaseId: number;
  userId: string;
}

export interface EmbedToken {
  token: string;
  databaseId: number;
  embedUrl: string;
  iframeCode: string;
  createdAt: string;
}

export interface EmbedDatabaseSnapshot {
  database: Database;
  tables: TableWithFields[];
}

export type ListDatabasesParams = {
  userId: string;
};

export type ListRecordsParams = {
  sortField?: string;
  sortDirection?: ListRecordsSortDirection;
  filterField?: string;
  filterValue?: string;
  search?: string;
};

export type ListRecordsSortDirection =
  (typeof ListRecordsSortDirection)[keyof typeof ListRecordsSortDirection];

export const ListRecordsSortDirection = {
  asc: "asc",
  desc: "desc",
} as const;
